# Generated by Django 2.1.5 on 2019-01-17 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pro_buyer',
        ),
        migrations.RemoveField(
            model_name='sellerproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='pro_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
