# Generated by Django 2.1.5 on 2019-01-17 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190117_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pro_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pro_buyer_back', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='sellerproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pro_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
