# Generated by Django 2.1.5 on 2019-01-17 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_buyeruserdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pro_buyer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='pro_buyer',
            field=models.ManyToManyField(blank=True, null=True, related_name='_customuser_pro_buyer_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
