# Generated by Django 2.1.5 on 2019-01-17 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190117_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pro_buyer',
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='buyer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
